<div style="border:solid Chocolate 2px; padding: 40px">

Сергей привет, меня зовут Станислав, и я буду проверять твой проект. Предлагаю общаться на «ты», но если это неудобно - дай знать, и мы перейдем на «вы».
Это учебный проект и здесь не стоит бояться делать ошибки, я хочу поделиться своим опытом и помочь тебе стать аналитиком данных.
Уже выполнена большая работа над проектом, давай сделаем его еще лучше. Ниже ты найдешь мои комментарии - пожалуйста, не перемещай, не изменяй и не удаляй их. Я буду использовать цветовую разметку:

<div class="alert alert-danger">
❌ <b>Комментарий с замечанием ревьюера:</b> Так выделены самые важные замечания. Как только ты их исправишь проект будет принят. </div>

<div class="alert alert-warning">
⚠️  <b>Комментарий с небольшим замечанием или советом ревьюера:</b> Так выделены небольшие замечания или советы. 
</div>

<div class="alert alert-success">
✔️ <b>Комментарий с комплиментом ревьюера:</b> Так я выделяю все остальные комментарии.</div>

Давай работать над проектом в диалоге: если ты что-то меняешь в проекте или отвечаешь на мои комментарии — пиши об этом.
Мне будет легче отследить изменения, если ты выделишь свои комментарии:
<div class="alert alert-info"> <b>🎓 Комментарий студента:</b> Например, вот так.</div>
Всё это поможет выполнить повторную проверку твоего проекта оперативнее.
</div>

<div class="alert alert-warning">
⚠️  <b>Комментарий с небольшим замечанием или советом ревьюера:</b>

Для того, чтобы сразу понять, о чем проект, в начале лучше добавить:
    
- краткое описание проекта;

- описание данных;

- план работы;

- цель проекта;
    
- заголовок.

</div>

<div class="alert alert-info"> <b>🎓 Комментарий студента:</b> Привет, Станислав! Спасибо за комментарии. Исправляюсь и добавляю описание:</div>

<div class="alert alert-success">
✔️ <b>Комментарий с комплиментом ревьюера в2:</b> 

Отличное описание, молодец!

# Анализ текущего уровня потребительской лояльности

## Описание проекта

**Заказчик:** крупная телекоммуникационная компания, предоставляющая свои услуги в странах СНГ.

**Задача:** определить текущий уровень потребительской лояльности (NPS - Net Promoter Score) среди клиентов из России.

**Источник данных:** для определения уровня лояльности компания провела опрос среди своих клиентов. Клиентам задавали классический вопрос: «Оцените по шкале от 1 до 10 вероятность того, что вы порекомендуете компанию друзьям и знакомым».

**Методика расчета NPS:** Чтобы оценить результаты опроса, оценки обычно делят на три группы:

9-10 баллов — «cторонники» (promoters);

7-8 баллов — «нейтралы» (passives);

0-6 баллов — «критики» (detractors).

Итоговое значение NPS рассчитывается по формуле: % «сторонников» - % «критиков».

### Описание данных

Данные представлены следующими таблицами:

* `user` - содержит основную информацию о клиентах и первичные ключи к остальным таблицам;

* `location` - справочник территорий, в которых телеком-компания оказывает услуги;

* `age_segment` - данные о возрастных сегментах клиентов;

* `traffic_segment` - данные о выделяемых сегментах по объёму потребляемого трафика;

* `lifetime_segment` - данные о выделяемых сегментах по количеству месяцев «жизни» клиента (как давно пользователь является клиентом компании).

## План работы

1. Подключение к базе
2. Выгрузка данных
3. Создание дашборда в Tableau

### Подключение к базе

In [1]:
import os
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

In [2]:
path_to_db_local = 'telecomm_csi.db'
path_to_db_platform = '/datasets/telecomm_csi.db'
path_to_db = None

if os.path.exists(path_to_db_local):
    path_to_db = path_to_db_local
elif os.path.exists(path_to_db_platform):
    path_to_db = path_to_db_platform
else:
    raise Exception('Файл с базой данных SQLite не найден!')

if path_to_db:
    engine = create_engine(f'sqlite:///{path_to_db}', echo=False)

In [3]:
query = """
SELECT *
FROM user;
"""

In [4]:
df = pd.read_sql(query, engine)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502493 entries, 0 to 502492
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user_id         502493 non-null  object
 1   lt_day          502493 non-null  int64
 2   age             501939 non-null  float64
 3   gender_segment  501192 non-null  float64
 4   os_name         502493 non-null  object
 5   cpe_type_name   502493 non-null  object
 6   location_id     502493 non-null  int64
 7   age_gr_id       502493 non-null  int64
 8   tr_gr_id        502493 non-null  int64
 9   lt_gr_id        502493 non-null  int64
 10  nps_score       502493 non-null  int64
dtypes: float64(2), int64(6), object(3)
memory usage: 42.2+ MB

In [5]:
df.head(3)

,user_id,lt_day,age,gender_segment,os_name,cpe_type_name,location_id,age_gr_id,tr_gr_id,lt_gr_id,nps_score
0,A001A2,2320,45.0,1.0,ANDROID,SMARTPHONE,55,5,5,8,10
1,A001WF,2344,53.0,0.0,ANDROID,SMARTPHONE,21,5,5,8,10
2,A003Q7,467,57.0,0.0,ANDROID,SMARTPHONE,28,6,9,6,10

In [6]:
query = """
SELECT *
FROM location;
"""

In [7]:
dfl = pd.read_sql(query, engine)
dfl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location_id  62 non-null     int64
 1   city         62 non-null     object
 2   country      62 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.6+ KB

In [8]:
query = """
SELECT *
FROM age_segment;
"""

In [9]:
dfa = pd.read_sql(query, engine)
dfa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age_gr_id   8 non-null      int64
 1   bucket_min  6 non-null      float64
 2   bucket_max  6 non-null      float64
 3   title       8 non-null      object
dtypes: float64(2), int64(1), object(1)
memory usage: 384.0+ bytes

In [10]:
query = """
SELECT *
FROM traffic_segment;
"""

In [11]:
dft = pd.read_sql(query, engine)
dft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tr_gr_id    25 non-null     int64
 1   bucket_min  25 non-null     float64
 2   bucket_max  24 non-null     float64
 3   title       25 non-null     object
dtypes: float64(2), int64(1), object(1)
memory usage: 928.0+ bytes

In [12]:
query = """
SELECT *
FROM lifetime_segment;
"""

In [13]:
dff = pd.read_sql(query, engine)
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   lt_gr_id    8 non-null      int64
 1   bucket_min  8 non-null      float64
 2   bucket_max  7 non-null      float64
 3   title       8 non-null      object
dtypes: float64(2), int64(1), object(1)
memory usage: 384.0+ bytes

### Выгрузка данных

Для дальнейшей обработки данных и постороения дашбордов необходимо получить таблицу со следующими параметрами:

| Parameter         | Description                                                                   | 
|-------------------|-------------------------------------------------------------------------------|
| user_id	        | Идентификатор клиента                                                         | 
| lt_day	        | Количество дней «жизни» клиента                                               | 
| is_new	        | Поле хранит информацию о том, является ли клиент новым                        |
| age	            | Возраст                                                                       |
| gender_segment	| Пол (для удобства работы с полем преобразуйте значения в текстовый вид)       |
| os_name	        | Тип операционной системы                                                      |
| cpe_type_name	    | Тип устройства                                                                | 
| country	        | Страна проживания                                                             | 
| city	            | Город проживания                                                              |
| age_segment	    | Возрастной сегмент                                                            |
| traffic_segment    | Сегмент по объёму потребляемого трафика                                       |
| lifetime_segment  | Сегмент по количеству дней «жизни»                                            | 
| nps_score	        | Оценка клиента в NPS-опросе                                                   |
| nps_group	        | Поле хранит информацию о том, к какой группе относится оценка клиента в опросе|

In [14]:
query = """
SELECT u.user_id,
u.lt_day,
    CASE
        WHEN u.lt_day <= 365 THEN True
        ELSE False
    END as is_new,
u.age,
    CASE
        WHEN u.gender_segment = 1 THEN 'women'
        WHEN u.gender_segment = 0 THEN 'men'
        ELSE 'nd'
    END as gender_segment,
u.os_name,
u.cpe_type_name,
l.country,
l.city,
a.title as age_segment,
t.title as traffic_segment,
f.title as lifetime_segment,
u.nps_score,
    CASE
        WHEN u.nps_score <= 6 THEN 'detractors'
        WHEN u.nps_score > 6 AND u.nps_score <= 8 THEN 'passives'
        ELSE 'promoters'
    END as nps_group
FROM user as u JOIN location as l ON u.location_id = l.location_id
    JOIN age_segment as a ON u.age_gr_id = a.age_gr_id
    JOIN traffic_segment as t ON u.tr_gr_id = t.tr_gr_id
    JOIN lifetime_segment as f ON u.lt_gr_id = f.lt_gr_id;
"""

In [15]:
dfj = pd.read_sql(query, engine)
dfj.head(10)

,user_id,lt_day,is_new,age,gender_segment,os_name,cpe_type_name,country,city,age_segment,traffic_segment,lifetime_segment,nps_score,nps_group
0,A001A2,2320,0,45.0,women,ANDROID,SMARTPHONE,Россия,Уфа,05 45-54,04 1-5,08 36+,10,promoters
1,A001WF,2344,0,53.0,men,ANDROID,SMARTPHONE,Россия,Киров,05 45-54,04 1-5,08 36+,10,promoters
2,A003Q7,467,0,57.0,men,ANDROID,SMARTPHONE,Россия,Москва,06 55-64,08 20-25,06 13-24,10,promoters
3,A004TB,4190,0,44.0,women,IOS,SMARTPHONE,Россия,РостовнаДону,04 35-44,03 0.1-1,08 36+,10,promoters
4,A004XT,1163,0,24.0,men,ANDROID,SMARTPHONE,Россия,Рязань,02 16-24,05 5-10,08 36+,10,promoters
5,A005O0,5501,0,42.0,women,ANDROID,SMARTPHONE,Россия,Омск,04 35-44,05 5-10,08 36+,6,detractors
6,A0061R,1236,0,45.0,men,ANDROID,SMARTPHONE,Россия,Уфа,05 45-54,06 10-15,08 36+,10,promoters
7,A009KS,313,1,35.0,men,ANDROID,SMARTPHONE,Россия,Москва,04 35-44,13 45-50,05 7-12,10,promoters
8,A00AES,3238,0,36.0,women,ANDROID,SMARTPHONE,Россия,СанктПетербург,04 35-44,04 1-5,08 36+,10,promoters
9,A00F70,4479,0,54.0,women,ANDROID,SMARTPHONE,Россия,Волгоград,05 45-54,07 15-20,08 36+,9,promoters

<div class="alert alert-success">
✔️ <b>Комментарий с комплиментом ревьюера:</b> 

Данные выгружены корректно, молодец. 
    
Здорово, что выведена информация по полученному датасету.

</div>

### Создание дашборда в Tableau

In [16]:
dfj.to_csv('telecomm_csi_tableau.csv', index=False)

Ссылка на проект в Tableau:
https://public.tableau.com/views/StudentprojectTelecom/Story1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link

<div class="alert alert-success">
✔️ <b>Комментарий с комплиментом ревьюера по Дашборду:</b>

    
Отличный анализ групп по пользователям, добавлены графики по основным категориям: полу, возрасту, городам, выведено соотношение новых и старых пользователей, добавлены все необходимые фильтры.
    
Здорово, что сделан анализ по группам.
    
Добавлен подробный анализ NPS по нескольким разрезам.
</div>

<div class="alert alert-danger">
❌ <b>Комментарий с замечанием ревьюера по Дашборду:</b> 

Есть замечание, которое необходимо скорректировать:    

   
- доработай, пожалуйста, анализ участников по городам, у нас много городов в базе и важно проанализировать их всех
    

</div>

<div class="alert alert-info"> <b>🎓 Комментарий студента:</b> Добавил анализ по городам.
Ссылка на доработанный проект:
    
https://public.tableau.com/shared/DBHM5GD4T?:display_count=n&:origin=viz_share_link
    
</div>

<div class="alert alert-success">
✔️ <b>Комментарий с комплиментом ревьюера в2:</b> 

Отлично